// src/constants/taskConstants.js
export const FETCH_ASSIGNED_TASKS_REQUEST = "FETCH_ASSIGNED_TASKS_REQUEST";
export const FETCH_ASSIGNED_TASKS_SUCCESS = "FETCH_ASSIGNED_TASKS_SUCCESS";
export const FETCH_ASSIGNED_TASKS_FAIL = "FETCH_ASSIGNED_TASKS_FAIL";

export const UPDATE_TASK_STATUS_REQUEST = "UPDATE_TASK_STATUS_REQUEST";
export const UPDATE_TASK_STATUS_SUCCESS = "UPDATE_TASK_STATUS_SUCCESS";
export const UPDATE_TASK_STATUS_FAIL = "UPDATE_TASK_STATUS_FAIL";

export const ADD_NEW_TASK_REQUEST = "ADD_NEW_TASK_REQUEST";
export const ADD_NEW_TASK_SUCCESS = "ADD_NEW_TASK_SUCCESS";
export const ADD_NEW_TASK_FAIL = "ADD_NEW_TASK_FAIL";

export const CLEAR_TASK_ERRORS = "CLEAR_TASK_ERRORS";
